server:
  port: 8001
  servlet:
    context path: "/profile/v1"

spring:
  application:
    name: profile-mgmt
  mvc:
    path match:
      matching-strategy: ant-path-matcher

  data:
    mongodb:
      user: admin
      password: admin
      database: medicus-connect
      uri: mongodb://localhost:27017

  config:
    rest:
      service: